#cloud-config

coreos:
  units:
    - name: myetcd.service
      command: start
      content: |
        [Unit]
        Description=Runs a command
        Requires=docker.service
        After=docker.service

        [Service]
        Type=oneshot
        ExecStart=/bin/sh -c '/usr/bin/docker run -d --net=host --name etcd quay.io/coreos/etcd:v2.0.3 -proxy on -listen-client-urls http://127.0.0.1:4001 -initial-cluster etcd0=http://master:2380'
    - name: calico.service
      command: start
      content: |
        [Unit]
        Description=Run calico
        Requires=docker.service
        After=docker.service myetcd.service

        [Service]
        Type=oneshot
        ExecStart=/bin/sh -c 'wget https://github.com/Metaswitch/calico-docker/releases/download/v0.0.6/calicoctl;chmod +x calicoctl;sudo /calicoctl node --ip=$private_ipv4'