#cloud-config

coreos:
  # Don't use the etcd.service provided by CoreOS. We'll use our own so we can get the latest version.
  units:
    # This service might block SSH from being set up. We'll just have to be patient.
   - name: myetcd.service
     command: start
     content: |
       [Unit]
       Description=Runs a command
       Requires=docker.service
       After=docker.service

       [Service]
       Type=oneshot
       ExecStart=/bin/sh -c "docker run -d -p 4001:4001 -p 2380:2380 -p 2379:2379 --name etcd quay.io/coreos/etcd:v2.0.3  -name etcd0  -advertise-client-urls http://$private_ipv4:2379,http://$private_ipv4:4001  -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001  -initial-advertise-peer-urls http://$private_ipv4:2380  -listen-peer-urls http://0.0.0.0:2380  -initial-cluster-token etcd-cluster-1  -initial-cluster etcd0=http://$private_ipv4:2380  -initial-cluster-state new"
